//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVuSuDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DichVuSuDung()
        {
            this.DatPhong = new HashSet<DatPhong>();
        }
    
        public int IDDichVuSuDung { get; set; }
        public Nullable<int> XeID { get; set; }
        public Nullable<int> MonAnID { get; set; }
        public Nullable<int> GiatUiID { get; set; }
        public Nullable<int> SpaID { get; set; }
        public Nullable<int> HoaDonID { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public Nullable<int> NguoiDungID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong> DatPhong { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        public virtual MonAn MonAn { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Spa Spa { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
