//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.DichVuSuDung = new HashSet<DichVuSuDung>();
        }
    
        public int HoaDonID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<int> PhongID { get; set; }
        public Nullable<System.DateTime> NgayNhanPhong { get; set; }
        public Nullable<System.DateTime> NgayTraPhong { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> IDDichVuSuDung { get; set; }
        public Nullable<int> NguoiDungID { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public string TrangThaiThanhToan { get; set; }
        public bool IsPaid => TrangThaiThanhToan == "Đã thanh toán";

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVuSuDung> DichVuSuDung { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
