//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiPhong
    {
        public int IDLoai { get; set; }
        public List<LoaiPhong> ListLoai { get; internal set; }
        public string TenLoai { get; set; }
    }
}
