//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        public int LuongID { get; set; }
        public int NhanVienID { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public decimal LuongMotGio { get; set; }
        public decimal TongLuong { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
